### ISSUE TITLE
Visual glitch while exporting encrypted wallet

### ISSUE THREAD

**Issue by panta82** [safex/safex_wallet#25]
![image](https://user-images.githubusercontent.com/4291324/39097204-9921e242-4659-11e8-9321-0eb1547525a5.png)

**Comment by Kiu0612** [comment]
This bug has been fixed in the new version of the wallet.
It has been tested on Mac OS and Windows.

![40880575-f783cfe2-66b3-11e8-8a71-f5faaa65e5d7](https://user-images.githubusercontent.com/20647765/40881721-4c8caec2-66ce-11e8-8978-5a504d3c1033.png)

@ddabek Please review the new version and close the issue.
